language: node_js
node_js:
  - "4"
  - "6"
  - "node"
sudo: false
install: npm install
script:
  - npm test
  - npm run test-karma
notifications:
  email:
    on_success: change
    on_failure: change
